Class {
	#name : #BalanceSheet,
	#superclass : #Object,
	#instVars : [
		'year',
		'quarter',
		'source',
		'cashAndCashEquivalents',
		'shortTermInvestments',
		'accountsReceivable',
		'inventory',
		'prepaidExpenses',
		'propertyPlantAndEquipment',
		'intangibleAssets',
		'goodwill',
		'longTermInvestments',
		'otherAssets',
		'marketableSecurities',
		'deferredAssets',
		'loansAndNotesReceivable',
		'equityInvestments',
		'leaseholdImprovements',
		'researchAndDevelopmentCosts',
		'depositsAndOtherAssets',
		'deferredTaxAssets',
		'depositsAndAdvances',
		'restrictedCash',
		'rightOfUseAssets',
		'derivativeAssets',
		'deferredCharges',
		'noncurrentAssetsHeldForSale',
		'otherNoncurrentAssets',
		'accountsPayable',
		'accruedExpenses',
		'shortTermDebt',
		'currentPortionOfLongTermDebt',
		'deferredRevenue',
		'longTermDebt',
		'deferredTaxLiabilities',
		'otherLiabilities',
		'pensionAndPostEmploymentBenefitObligations',
		'leaseObligations',
		'incomeTaxPayable',
		'warrantyObiligation',
		'contingentLiabilities',
		'derivativeLiabilities',
		'environmentalObligations',
		'employeeBenefitLiabilities',
		'incomeTaxesPayable',
		'warrantyObligations',
		'environmentLiabilities',
		'otherNonCurrentLiabilities',
		'commonStock',
		'preferredStock',
		'additionalPaidInCapital',
		'retainedEarnings',
		'treasuryStock',
		'accumulatedOtherComprehensiveIncome',
		'noncontrollingInterest',
		'redeemableNoncontrollingInterest',
		'sharebasedCompensation',
		'minorityInterest',
		'capitalLeases',
		'unearnedRevenue',
		'customerAdvances',
		'debtIssuanceCosts',
		'accumulatedDepreciationAndAmortization',
		'assetsRetirementObligations',
		'operationalLeases',
		'pensionPlanAssetsAndLiabilities',
		'assetsHeldForSale',
		'repossessedAssets',
		'currentAssetsHeldForSale',
		'discontinuedOperations',
		'redeemablePreferredStock',
		'accumulatedOtherComprehensive',
		'dividendsPayable',
		'accumulatedEarnings',
		'accumulatedDeficit',
		'stockholdersEquityAttributableToNoncontrollingInterest'
	],
	#category : #'teleapp-orion-company'
}

{ #category : #accessing }
BalanceSheet >> accountsPayable [

	^ accountsPayable
]

{ #category : #accessing }
BalanceSheet >> accountsPayable: anObject [

	accountsPayable := anObject
]

{ #category : #accessing }
BalanceSheet >> accountsReceivable [

	^ accountsReceivable
]

{ #category : #accessing }
BalanceSheet >> accountsReceivable: anObject [

	accountsReceivable := anObject
]

{ #category : #accessing }
BalanceSheet >> accruedExpenses [

	^ accruedExpenses
]

{ #category : #accessing }
BalanceSheet >> accruedExpenses: anObject [

	accruedExpenses := anObject
]

{ #category : #accessing }
BalanceSheet >> accumulatedDeficit [

	^ accumulatedDeficit
]

{ #category : #accessing }
BalanceSheet >> accumulatedDeficit: anObject [

	accumulatedDeficit := anObject
]

{ #category : #accessing }
BalanceSheet >> accumulatedDepreciationAndAmortization [

	^ accumulatedDepreciationAndAmortization
]

{ #category : #accessing }
BalanceSheet >> accumulatedDepreciationAndAmortization: anObject [

	accumulatedDepreciationAndAmortization := anObject
]

{ #category : #accessing }
BalanceSheet >> accumulatedEarnings [

	^ accumulatedEarnings
]

{ #category : #accessing }
BalanceSheet >> accumulatedEarnings: anObject [

	accumulatedEarnings := anObject
]

{ #category : #accessing }
BalanceSheet >> accumulatedOtherComprehensive [

	^ accumulatedOtherComprehensive
]

{ #category : #accessing }
BalanceSheet >> accumulatedOtherComprehensive: anObject [

	accumulatedOtherComprehensive := anObject
]

{ #category : #accessing }
BalanceSheet >> accumulatedOtherComprehensiveIncome [

	^ accumulatedOtherComprehensiveIncome
]

{ #category : #accessing }
BalanceSheet >> accumulatedOtherComprehensiveIncome: anObject [

	accumulatedOtherComprehensiveIncome := anObject
]

{ #category : #accessing }
BalanceSheet >> additionalPaidInCapital [

	^ additionalPaidInCapital
]

{ #category : #accessing }
BalanceSheet >> additionalPaidInCapital: anObject [

	additionalPaidInCapital := anObject
]

{ #category : #accessing }
BalanceSheet >> assetsHeldForSale [

	^ assetsHeldForSale
]

{ #category : #accessing }
BalanceSheet >> assetsHeldForSale: anObject [

	assetsHeldForSale := anObject
]

{ #category : #accessing }
BalanceSheet >> assetsRetirementObligations [

	^ assetsRetirementObligations
]

{ #category : #accessing }
BalanceSheet >> assetsRetirementObligations: anObject [

	assetsRetirementObligations := anObject
]

{ #category : #accessing }
BalanceSheet >> capitalLeases [

	^ capitalLeases
]

{ #category : #accessing }
BalanceSheet >> capitalLeases: anObject [

	capitalLeases := anObject
]

{ #category : #accessing }
BalanceSheet >> cashAndCashEquivalents [

	^ cashAndCashEquivalents
]

{ #category : #accessing }
BalanceSheet >> cashAndCashEquivalents: anObject [

	cashAndCashEquivalents := anObject
]

{ #category : #accessing }
BalanceSheet >> commonStock [

	^ commonStock
]

{ #category : #accessing }
BalanceSheet >> commonStock: anObject [

	commonStock := anObject
]

{ #category : #accessing }
BalanceSheet >> contingentLiabilities [

	^ contingentLiabilities
]

{ #category : #accessing }
BalanceSheet >> contingentLiabilities: anObject [

	contingentLiabilities := anObject
]

{ #category : #accessing }
BalanceSheet >> currentAssetsHeldForSale [

	^ currentAssetsHeldForSale
]

{ #category : #accessing }
BalanceSheet >> currentAssetsHeldForSale: anObject [

	currentAssetsHeldForSale := anObject
]

{ #category : #accessing }
BalanceSheet >> currentPortionOfLongTermDebt [

	^ currentPortionOfLongTermDebt
]

{ #category : #accessing }
BalanceSheet >> currentPortionOfLongTermDebt: anObject [

	currentPortionOfLongTermDebt := anObject
]

{ #category : #accessing }
BalanceSheet >> customerAdvances [

	^ customerAdvances
]

{ #category : #accessing }
BalanceSheet >> customerAdvances: anObject [

	customerAdvances := anObject
]

{ #category : #accessing }
BalanceSheet >> debtIssuanceCosts [

	^ debtIssuanceCosts
]

{ #category : #accessing }
BalanceSheet >> debtIssuanceCosts: anObject [

	debtIssuanceCosts := anObject
]

{ #category : #accessing }
BalanceSheet >> deferredAssets [

	^ deferredAssets
]

{ #category : #accessing }
BalanceSheet >> deferredAssets: anObject [

	deferredAssets := anObject
]

{ #category : #accessing }
BalanceSheet >> deferredCharges [

	^ deferredCharges
]

{ #category : #accessing }
BalanceSheet >> deferredCharges: anObject [

	deferredCharges := anObject
]

{ #category : #accessing }
BalanceSheet >> deferredRevenue [

	^ deferredRevenue
]

{ #category : #accessing }
BalanceSheet >> deferredRevenue: anObject [

	deferredRevenue := anObject
]

{ #category : #accessing }
BalanceSheet >> deferredTaxAssets [

	^ deferredTaxAssets
]

{ #category : #accessing }
BalanceSheet >> deferredTaxAssets: anObject [

	deferredTaxAssets := anObject
]

{ #category : #accessing }
BalanceSheet >> deferredTaxLiabilities [

	^ deferredTaxLiabilities
]

{ #category : #accessing }
BalanceSheet >> deferredTaxLiabilities: anObject [

	deferredTaxLiabilities := anObject
]

{ #category : #accessing }
BalanceSheet >> depositsAndAdvances [

	^ depositsAndAdvances
]

{ #category : #accessing }
BalanceSheet >> depositsAndAdvances: anObject [

	depositsAndAdvances := anObject
]

{ #category : #accessing }
BalanceSheet >> depositsAndOtherAssets [

	^ depositsAndOtherAssets
]

{ #category : #accessing }
BalanceSheet >> depositsAndOtherAssets: anObject [

	depositsAndOtherAssets := anObject
]

{ #category : #accessing }
BalanceSheet >> derivativeAssets [

	^ derivativeAssets
]

{ #category : #accessing }
BalanceSheet >> derivativeAssets: anObject [

	derivativeAssets := anObject
]

{ #category : #accessing }
BalanceSheet >> derivativeLiabilities [

	^ derivativeLiabilities
]

{ #category : #accessing }
BalanceSheet >> derivativeLiabilities: anObject [

	derivativeLiabilities := anObject
]

{ #category : #accessing }
BalanceSheet >> discontinuedOperations [

	^ discontinuedOperations
]

{ #category : #accessing }
BalanceSheet >> discontinuedOperations: anObject [

	discontinuedOperations := anObject
]

{ #category : #accessing }
BalanceSheet >> dividendsPayable [

	^ dividendsPayable
]

{ #category : #accessing }
BalanceSheet >> dividendsPayable: anObject [

	dividendsPayable := anObject
]

{ #category : #accessing }
BalanceSheet >> employeeBenefitLiabilities [

	^ employeeBenefitLiabilities
]

{ #category : #accessing }
BalanceSheet >> employeeBenefitLiabilities: anObject [

	employeeBenefitLiabilities := anObject
]

{ #category : #accessing }
BalanceSheet >> environmentLiabilities [

	^ environmentLiabilities
]

{ #category : #accessing }
BalanceSheet >> environmentLiabilities: anObject [

	environmentLiabilities := anObject
]

{ #category : #accessing }
BalanceSheet >> environmentalObligations [

	^ environmentalObligations
]

{ #category : #accessing }
BalanceSheet >> environmentalObligations: anObject [

	environmentalObligations := anObject
]

{ #category : #accessing }
BalanceSheet >> equityInvestments [

	^ equityInvestments
]

{ #category : #accessing }
BalanceSheet >> equityInvestments: anObject [

	equityInvestments := anObject
]

{ #category : #accessing }
BalanceSheet >> goodwill [

	^ goodwill
]

{ #category : #accessing }
BalanceSheet >> goodwill: anObject [

	goodwill := anObject
]

{ #category : #accessing }
BalanceSheet >> incomeTaxPayable [

	^ incomeTaxPayable
]

{ #category : #accessing }
BalanceSheet >> incomeTaxPayable: anObject [

	incomeTaxPayable := anObject
]

{ #category : #accessing }
BalanceSheet >> incomeTaxesPayable [

	^ incomeTaxesPayable
]

{ #category : #accessing }
BalanceSheet >> incomeTaxesPayable: anObject [

	incomeTaxesPayable := anObject
]

{ #category : #accessing }
BalanceSheet >> intangibleAssets [

	^ intangibleAssets
]

{ #category : #accessing }
BalanceSheet >> intangibleAssets: anObject [

	intangibleAssets := anObject
]

{ #category : #accessing }
BalanceSheet >> inventory [

	^ inventory
]

{ #category : #accessing }
BalanceSheet >> inventory: anObject [

	inventory := anObject
]

{ #category : #accessing }
BalanceSheet >> leaseObligations [

	^ leaseObligations
]

{ #category : #accessing }
BalanceSheet >> leaseObligations: anObject [

	leaseObligations := anObject
]

{ #category : #accessing }
BalanceSheet >> leaseholdImprovements [

	^ leaseholdImprovements
]

{ #category : #accessing }
BalanceSheet >> leaseholdImprovements: anObject [

	leaseholdImprovements := anObject
]

{ #category : #accessing }
BalanceSheet >> loansAndNotesReceivable [

	^ loansAndNotesReceivable
]

{ #category : #accessing }
BalanceSheet >> loansAndNotesReceivable: anObject [

	loansAndNotesReceivable := anObject
]

{ #category : #accessing }
BalanceSheet >> longTermDebt [

	^ longTermDebt
]

{ #category : #accessing }
BalanceSheet >> longTermDebt: anObject [

	longTermDebt := anObject
]

{ #category : #accessing }
BalanceSheet >> longTermInvestments [

	^ longTermInvestments
]

{ #category : #accessing }
BalanceSheet >> longTermInvestments: anObject [

	longTermInvestments := anObject
]

{ #category : #accessing }
BalanceSheet >> marketableSecurities [

	^ marketableSecurities
]

{ #category : #accessing }
BalanceSheet >> marketableSecurities: anObject [

	marketableSecurities := anObject
]

{ #category : #accessing }
BalanceSheet >> minorityInterest [

	^ minorityInterest
]

{ #category : #accessing }
BalanceSheet >> minorityInterest: anObject [

	minorityInterest := anObject
]

{ #category : #accessing }
BalanceSheet >> noncontrollingInterest [

	^ noncontrollingInterest
]

{ #category : #accessing }
BalanceSheet >> noncontrollingInterest: anObject [

	noncontrollingInterest := anObject
]

{ #category : #accessing }
BalanceSheet >> noncurrentAssetsHeldForSale [

	^ noncurrentAssetsHeldForSale
]

{ #category : #accessing }
BalanceSheet >> noncurrentAssetsHeldForSale: anObject [

	noncurrentAssetsHeldForSale := anObject
]

{ #category : #accessing }
BalanceSheet >> operationalLeases [

	^ operationalLeases
]

{ #category : #accessing }
BalanceSheet >> operationalLeases: anObject [

	operationalLeases := anObject
]

{ #category : #accessing }
BalanceSheet >> otherAssets [

	^ otherAssets
]

{ #category : #accessing }
BalanceSheet >> otherAssets: anObject [

	otherAssets := anObject
]

{ #category : #accessing }
BalanceSheet >> otherLiabilities [

	^ otherLiabilities
]

{ #category : #accessing }
BalanceSheet >> otherLiabilities: anObject [

	otherLiabilities := anObject
]

{ #category : #accessing }
BalanceSheet >> otherNonCurrentLiabilities [

	^ otherNonCurrentLiabilities
]

{ #category : #accessing }
BalanceSheet >> otherNonCurrentLiabilities: anObject [

	otherNonCurrentLiabilities := anObject
]

{ #category : #accessing }
BalanceSheet >> otherNoncurrentAssets [

	^ otherNoncurrentAssets
]

{ #category : #accessing }
BalanceSheet >> otherNoncurrentAssets: anObject [

	otherNoncurrentAssets := anObject
]

{ #category : #accessing }
BalanceSheet >> pensionAndPostEmploymentBenefitObligations [

	^ pensionAndPostEmploymentBenefitObligations
]

{ #category : #accessing }
BalanceSheet >> pensionAndPostEmploymentBenefitObligations: anObject [

	pensionAndPostEmploymentBenefitObligations := anObject
]

{ #category : #accessing }
BalanceSheet >> pensionPlanAssetsAndLiabilities [

	^ pensionPlanAssetsAndLiabilities
]

{ #category : #accessing }
BalanceSheet >> pensionPlanAssetsAndLiabilities: anObject [

	pensionPlanAssetsAndLiabilities := anObject
]

{ #category : #accessing }
BalanceSheet >> preferredStock [

	^ preferredStock
]

{ #category : #accessing }
BalanceSheet >> preferredStock: anObject [

	preferredStock := anObject
]

{ #category : #accessing }
BalanceSheet >> prepaidExpenses [

	^ prepaidExpenses
]

{ #category : #accessing }
BalanceSheet >> prepaidExpenses: anObject [

	prepaidExpenses := anObject
]

{ #category : #accessing }
BalanceSheet >> propertyPlantAndEquipment [

	^ propertyPlantAndEquipment
]

{ #category : #accessing }
BalanceSheet >> propertyPlantAndEquipment: anObject [

	propertyPlantAndEquipment := anObject
]

{ #category : #accessing }
BalanceSheet >> quarter [

	^ quarter
]

{ #category : #accessing }
BalanceSheet >> quarter: anObject [

	quarter := anObject
]

{ #category : #accessing }
BalanceSheet >> redeemableNoncontrollingInterest [

	^ redeemableNoncontrollingInterest
]

{ #category : #accessing }
BalanceSheet >> redeemableNoncontrollingInterest: anObject [

	redeemableNoncontrollingInterest := anObject
]

{ #category : #accessing }
BalanceSheet >> redeemablePreferredStock [

	^ redeemablePreferredStock
]

{ #category : #accessing }
BalanceSheet >> redeemablePreferredStock: anObject [

	redeemablePreferredStock := anObject
]

{ #category : #accessing }
BalanceSheet >> repossessedAssets [

	^ repossessedAssets
]

{ #category : #accessing }
BalanceSheet >> repossessedAssets: anObject [

	repossessedAssets := anObject
]

{ #category : #accessing }
BalanceSheet >> researchAndDevelopmentCosts [

	^ researchAndDevelopmentCosts
]

{ #category : #accessing }
BalanceSheet >> researchAndDevelopmentCosts: anObject [

	researchAndDevelopmentCosts := anObject
]

{ #category : #accessing }
BalanceSheet >> restrictedCash [

	^ restrictedCash
]

{ #category : #accessing }
BalanceSheet >> restrictedCash: anObject [

	restrictedCash := anObject
]

{ #category : #accessing }
BalanceSheet >> retainedEarnings [

	^ retainedEarnings
]

{ #category : #accessing }
BalanceSheet >> retainedEarnings: anObject [

	retainedEarnings := anObject
]

{ #category : #accessing }
BalanceSheet >> rightOfUseAssets [

	^ rightOfUseAssets
]

{ #category : #accessing }
BalanceSheet >> rightOfUseAssets: anObject [

	rightOfUseAssets := anObject
]

{ #category : #accessing }
BalanceSheet >> sharebasedCompensation [

	^ sharebasedCompensation
]

{ #category : #accessing }
BalanceSheet >> sharebasedCompensation: anObject [

	sharebasedCompensation := anObject
]

{ #category : #accessing }
BalanceSheet >> shortTermDebt [

	^ shortTermDebt
]

{ #category : #accessing }
BalanceSheet >> shortTermDebt: anObject [

	shortTermDebt := anObject
]

{ #category : #accessing }
BalanceSheet >> shortTermInvestments [

	^ shortTermInvestments
]

{ #category : #accessing }
BalanceSheet >> shortTermInvestments: anObject [

	shortTermInvestments := anObject
]

{ #category : #accessing }
BalanceSheet >> source [

	^ source
]

{ #category : #accessing }
BalanceSheet >> source: anObject [

	source := anObject
]

{ #category : #accessing }
BalanceSheet >> stockholdersEquityAttributableToNoncontrollingInterest [

	^ stockholdersEquityAttributableToNoncontrollingInterest
]

{ #category : #accessing }
BalanceSheet >> stockholdersEquityAttributableToNoncontrollingInterest: anObject [

	stockholdersEquityAttributableToNoncontrollingInterest := anObject
]

{ #category : #accessing }
BalanceSheet >> treasuryStock [

	^ treasuryStock
]

{ #category : #accessing }
BalanceSheet >> treasuryStock: anObject [

	treasuryStock := anObject
]

{ #category : #accessing }
BalanceSheet >> unearnedRevenue [

	^ unearnedRevenue
]

{ #category : #accessing }
BalanceSheet >> unearnedRevenue: anObject [

	unearnedRevenue := anObject
]

{ #category : #accessing }
BalanceSheet >> warrantyObiligation [

	^ warrantyObiligation
]

{ #category : #accessing }
BalanceSheet >> warrantyObiligation: anObject [

	warrantyObiligation := anObject
]

{ #category : #accessing }
BalanceSheet >> warrantyObligations [

	^ warrantyObligations
]

{ #category : #accessing }
BalanceSheet >> warrantyObligations: anObject [

	warrantyObligations := anObject
]

{ #category : #accessing }
BalanceSheet >> year [

	^ year
]

{ #category : #accessing }
BalanceSheet >> year: anObject [

	year := anObject
]
